service: practicerepo-finch
provider:
  name: aws
  region: ap-northeast-2
  stage: dev

plugins:
  - serverless-finch

custom:
  client:
    bucketName: "${self:service}-${self:stage}"

# resources:
#   Resources:
#     S3BucketFinch:
#       Type: AWS::S3::Bucket
#       Properties:
#         BucketName: "${self:service}-finch-bucket"